#LOGGING CONFIGURATIONS
debug: true
logging:
  file:
    name: taskmanager.log
    path: /opt
  level:
    org:
      springframework.*: info
    br:
      eng:
        joaofaro:
          taskmanager: debug
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-dd-MM-yyyy HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(%X{UUID_TASK_MANAGER}){yellow} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    file: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-dd-MM-yyyy HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(%X{UUID_TASK_MANAGER}){yellow} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 30
#DATABASE
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:task-manager
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

#SERVER
server:
  port: 8000
#KEYCLOAK
keycloak:
  use-resource-role-mappings: true
  bearer-only: true
  realm: itau
  auth-server-url: http://localhost:8080/auth/
  ssl-required: external
  resource: task-manager-app
  credentials:
    secret: 0bf3bd99-2c54-4d6a-85cb-68db54944ddc